spring.application.name=study
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

spring.datasource.url=jdbc:postgresql://localhost:5432/studydb
spring.datasource.username=studyuser
spring.datasource.password=studypw

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.session.store-type=redis
spring.session.timeout=30m